[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; Configuramos la PSRAM de la forma más estándar posible
build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Eliminamos la línea del f_flash para que use el valor por defecto
; y no busque archivos de sistema que no tenemos.
board_build.arduino.memory_type = qio_opi

monitor_speed = 115200

lib_deps = 
    links2004/WebSockets@^2.6.1