[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Configuración de PSRAM para soporte de imágenes alta resolución
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM

; Gestión de dependencias automáticas
lib_deps = 
    links2004/WebSockets @ ^2.4.1
    espressif/esp32-camera @ ^2.0.4
